/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nobusue' at '14/09/14 12:53' with Gradle 2.1
 *
 * @author nobusue, @date 14/09/14 12:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
