/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'watabikitakuma' at '14/08/27 6:42' with Gradle 2.0
 *
 * @author watabikitakuma, @date 14/08/27 6:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
