import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'xxxx' at '14/08/03 23:10' with Gradle 2.0
 *
 * @author xxxx, @date 14/08/03 23:10
 */
public class LibraryTest {
  @Test public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
