/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xxxx' at '14/08/03 23:10' with Gradle 2.0
 *
 * @author xxxx, @date 14/08/03 23:10
 */
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
